const ADD_CONSTRUCTOR_BUN_ITEM = 'CONSTRUCTOR/ADD_BUN_ITEM'
const ADD_CONSTRUCTOR_INSIDE_ITEM = 'CONSTRUCTOR/ADD_INSIDE_ITEM'
const REMOVE_CONSTRUCTOR_INSIDE_ITEM = 'CONSTRUCTOR/REMOVE_INSIDE_ITEM'
const MOVE_CONSTRUCTOR_INSIDE_ITEM = 'CONSTRUCTOR/MOVE_INSIDE_ITEM'
const CLEAR_CONSTRUCTOR = 'CONSTRUCTOR/CLEAR'

export {
    ADD_CONSTRUCTOR_BUN_ITEM,
    ADD_CONSTRUCTOR_INSIDE_ITEM,
    REMOVE_CONSTRUCTOR_INSIDE_ITEM,
    MOVE_CONSTRUCTOR_INSIDE_ITEM,
    CLEAR_CONSTRUCTOR,
}