const ADD_CONSTRUCTOR_BUN_ITEM = 'ADD_CONSTRUCTOR_BUN_ITEM'
const ADD_CONSTRUCTOR_INSIDE_ITEM = 'ADD_CONSTRUCTOR_INSIDE_ITEM'
const REMOVE_CONSTRUCTOR_INSIDE_ITEM = 'REMOVE_CONSTRUCTOR_INSIDE_ITEM'
const MOVE_CONSTRUCTOR_INSIDE_ITEM = 'MOVE_CONSTRUCTOR_INSIDE_ITEM'

export {
    ADD_CONSTRUCTOR_BUN_ITEM,
    ADD_CONSTRUCTOR_INSIDE_ITEM,
    REMOVE_CONSTRUCTOR_INSIDE_ITEM,
    MOVE_CONSTRUCTOR_INSIDE_ITEM,
}